language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cp CNAME ./build/CNAME
  - npm install
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  target-branch: master
  on:
    branch: dev
